name: Android Build

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging
  workflow_dispatch:

jobs:
  build-android:
    name: Build Android APK/AAB
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies
        run: npm ci

      - name: Create production .env file
        run: |
          echo "VITE_BASE_API_URL=${{ secrets.VITE_BASE_API_URL }}" > .env.mobile
          echo "VITE_WS_URL=${{ secrets.VITE_WS_URL }}" >> .env.mobile
          echo "VITE_PUBLIC_POSTHOG_KEY=${{ secrets.VITE_PUBLIC_POSTHOG_KEY }}" >> .env.mobile
          echo "VITE_PUBLIC_POSTHOG_HOST=${{ secrets.VITE_PUBLIC_POSTHOG_HOST }}" >> .env.mobile

      - name: Build frontend for mobile
        run: npm run build:mobile

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Make gradlew executable
        working-directory: android
        run: chmod +x gradlew

      - name: Decode keystore
        working-directory: android
        run: |
          # Decode keystore from base64 and save to app directory
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > app/lia-release.keystore

      - name: Build Release APK/AAB
        working-directory: android
        env:
          KEYSTORE_FILE: ${{ github.workspace }}/android/app/lia-release.keystore
          KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: |
          # Build release APK and AAB
          ./gradlew assembleRelease bundleRelease

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: android/app/build/outputs/apk/release/app-release.apk
          retention-days: 30

      - name: Upload Release AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: android/app/build/outputs/bundle/release/app-release.aab
          retention-days: 30

      # Publish to Google Play Store (Internal Testing)
      - name: Upload to Play Store
        if: github.ref == 'refs/heads/staging' && github.event_name == 'push'
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
          packageName: pro.lia.app
          releaseFiles: android/app/build/outputs/bundle/release/app-release.aab
          track: internal
          status: completed
